language : scala
sudo: required

services:
  - docker

addons:
  hosts:
    - zookeeper
    - broker1
    - broker2
    - broker3

scala:
  - 2.11.8
  - 2.12.1

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

jdk:
  - oraclejdk8

install:
  - docker pull jplock/zookeeper:3.4.8
  - docker pull wurstmeister/kafka:0.8.2.0
  - docker pull wurstmeister/kafka:0.9.0.1
  - docker pull wurstmeister/kafka:0.10.0.0
  - docker pull wurstmeister/kafka:0.10.1.0
  - docker pull wurstmeister/kafka:0.10.2.0

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test


